### ISSUE TITLE
[Feature] Allow configuration of Scala version from the tool.

### ISSUE THREAD

**Issue by megri** [kitlangton/zio-start#2]
(I hope I'm not considered rude for opening issues for these feature requests…)

It would be neat to be able to choose the preconfigured Scala version from the website. Choosing a version should have an effect on the generated .scalafmt-file.

**Comment by kitlangton** [comment]
> (I hope I'm not considered rude for opening issues for these feature requests…)

Not at all! I greatly appreciate it :)

**Comment by megri** [comment]
> > (I hope I'm not considered rude for opening issues for these feature requests…)
> 
> Not at all! I greatly appreciate it :)

Well in that case..!

**Comment by megri** [comment]
I'm having a look at this issue as we speak; I've wanted to do something a bit more "official" in Laminar for a good time and it's pretty easy to find my way around the project. If you're open for contributions I'll give it a go and see what I come up with.

**Comment by kitlangton** [comment]
For sure! Give it a whirl :)

**Comment by megri** [comment]
https://github.com/kitlangton/zio-start/pull/6
